"""Core module - 核心异常、工作流状态、任务数据结构"""

from .exceptions import (
    FailureType,
    WorkflowError,
    ConfigError,
    NodeError,
    CalculationError,
    TransformError,
    InferError,
    SecurityError,
    ResourceError,
    GroupNotFoundError,
    HamiltonianNotFoundError,
    AbortException,
)

from .workflow_state import (
    EventType,
    ErrorRecord,
    MonitorState,
    MonitorEvent,
    MonitorConfig,
    WorkflowMonitor,
    JobMonitor,
    TaskError,
    ErrorTask,
    ErrorContext,
    record_error,
    append_error_task,
    get_task_retry_count,
)

from .tasks import (
    OlpTask,
    InferTask,
    CalcTask,
    read_tasks,
    write_tasks,
    read_olp_tasks,
    write_olp_tasks,
    append_olp_task,
    read_infer_tasks,
    write_infer_tasks,
    append_infer_task,
    read_calc_tasks,
    write_calc_tasks,
    append_calc_task,
    count_tasks,
)

__all__ = [
    # exceptions
    "FailureType",
    "WorkflowError",
    "ConfigError",
    "NodeError",
    "CalculationError",
    "TransformError",
    "InferError",
    "SecurityError",
    "ResourceError",
    "GroupNotFoundError",
    "HamiltonianNotFoundError",
    "AbortException",
    # workflow_state
    "EventType",
    "ErrorRecord",
    "MonitorState",
    "MonitorEvent",
    "MonitorConfig",
    "WorkflowMonitor",
    "JobMonitor",
    "TaskError",
    "ErrorTask",
    "ErrorContext",
    "record_error",
    "append_error_task",
    "get_task_retry_count",
    # tasks
    "OlpTask",
    "InferTask",
    "CalcTask",
    "read_tasks",
    "write_tasks",
    "read_olp_tasks",
    "write_olp_tasks",
    "append_olp_task",
    "read_infer_tasks",
    "write_infer_tasks",
    "append_infer_task",
    "read_calc_tasks",
    "write_calc_tasks",
    "append_calc_task",
    "count_tasks",
]
